dist: trusty
sudo: required
services:
  - docker
language: node_js
notifications:
  email: false
node_js:
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    # This is required to run new chrome on old trusty
      - libnss3
    # Things needed to run ledger
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libgtk2.0-0
      - libxtst6
      - libnotify4
      - libgconf2-4
      - libgtk2.0-0:i386
      - libxtst6:i386
      - libnotify4:i386
      - libgconf2-4:i386
      - libnss3:i386
      - libasound2:i386
      - libxss1:i386
      - socat
      - libusb-1.0-0-dev
      - libudev-dev
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn --pure-lockfile
before_script: greenkeeper-lockfile-update
script:
  - set -e                     # fail fast
  - yarn lint
  - yarn test:coverage
  - ./scripts/e2e.sh || true
after_script: greenkeeper-lockfile-upload
